'use client';

import { useEffect, useState } from 'react';
import { PencilSimple, Plus, Trash } from '@phosphor-icons/react';
import { Alert } from '@/components/ui/Alert';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardBody, CardHeader, CardTitle } from '@/components/ui/Card';
import { ConfirmDialog } from '@/components/ui/ConfirmDialog';
import { EmptyState } from '@/components/ui/EmptyState';
import { Input } from '@/components/ui/Input';
import { Modal } from '@/components/ui/Modal';
import { Select } from '@/components/ui/Select';
import { Table, TableContainer, TBody, TD, TH, THead, TR } from '@/components/ui/Table';
import { TableAction } from '@/components/ui/TableAction';
import { TableSkeleton } from '@/components/ui/Skeleton';
import { EPIC_COMPLEXITY_TYPES } from '@/lib/status-alert-rule-types';
import type { StatusAlertRule, StatusAlertRuleInput } from '@/lib/status-alert-rule-types';
import { TTM_TYPES } from '@/lib/ttm-policy-types';
import type { TtmPolicy, TtmPolicyInput } from '@/lib/ttm-policy-types';
import { compareValues, useSortableList } from '@/lib/use-sortable-list';

type RuleSortKey = 'epicComplexityType' | 'epicStatus' | 'earlyAlertOffsetDays' | 'lateAlertOffsetDays' | 'status';
type PolicySortKey = 'ttmType' | 'epicComplexityType' | 'fromTtmField' | 'toTtmField' | 'workingDays' | 'status';

interface Notice { text: string; type: 'error' | 'success'; }
const EMPTY_RULE: StatusAlertRuleInput = { earlyAlertOffsetDays: 0, epicComplexityType: 'SIMPLE', epicStatus: 'Design', isActive: true, lateAlertOffsetDays: 1 };
const EMPTY_POLICY: TtmPolicyInput = { epicComplexityType: 'SIMPLE', fromTtmField: 'START_DATE', isActive: true, toTtmField: 'R4G_DATE', ttmType: 'TTM_CNTT', workingDays: 15 };
const typeLabel = (value: 'SIMPLE' | 'COMPLEX') => value === 'SIMPLE' ? 'Epic đơn giản' : 'Epic phức tạp';
const offsetLabel = (value: number) => `T1 + ${value} ngày làm việc`;
const readError = (value: unknown, fallback: string) => typeof value === 'object' && value !== null && 'error' in value && typeof value.error === 'string' ? value.error : fallback;

export function StatusAlertRulesSettings() {
  const [rules, setRules] = useState<StatusAlertRule[]>([]); const [policies, setPolicies] = useState<TtmPolicy[]>([]);
  const [notice, setNotice] = useState<Notice | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [ruleForm, setRuleForm] = useState<StatusAlertRuleInput>(EMPTY_RULE); const [editingRule, setEditingRule] = useState<number | null>(null); const [ruleModal, setRuleModal] = useState(false);
  const [policyForm, setPolicyForm] = useState<TtmPolicyInput>(EMPTY_POLICY); const [editingPolicy, setEditingPolicy] = useState<number | null>(null); const [policyModal, setPolicyModal] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<{ id: number; kind: 'policy' | 'rule'; label: string } | null>(null);
  const load = async () => { setLoading(true); try { const [r, p] = await Promise.all([fetch('/api/status-alert-rules'), fetch('/api/ttm-policies')]); const [rv, pv]: unknown[] = await Promise.all([r.json(), p.json()]); if (!r.ok || !Array.isArray(rv)) throw new Error(readError(rv, 'Không thể tải rule cảnh báo.')); if (!p.ok || !Array.isArray(pv)) throw new Error(readError(pv, 'Không thể tải tiêu chí Time to Market.')); setRules(rv as StatusAlertRule[]); setPolicies(pv as TtmPolicy[]); } catch (error) { setNotice({ text: error instanceof Error ? error.message : 'Không thể tải cấu hình.', type: 'error' }); } finally { setLoading(false); } };
  useEffect(() => { void Promise.resolve().then(load); }, []);
  const saveRule = async () => { setSaving(true); try { const response = await fetch('/api/status-alert-rules', { method: editingRule === null ? 'POST' : 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editingRule === null ? ruleForm : { ...ruleForm, id: editingRule }) }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(readError(payload, 'Không thể lưu rule cảnh báo.')); setRuleModal(false); setNotice({ text: 'Đã lưu rule cảnh báo.', type: 'success' }); await load(); } catch (error) { setNotice({ text: error instanceof Error ? error.message : 'Không thể lưu rule cảnh báo.', type: 'error' }); } finally { setSaving(false); } };
  const savePolicy = async () => { setSaving(true); try { const response = await fetch('/api/ttm-policies', { method: editingPolicy === null ? 'POST' : 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(editingPolicy === null ? policyForm : { ...policyForm, id: editingPolicy }) }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(readError(payload, 'Không thể lưu tiêu chí Time to Market.')); setPolicyModal(false); setNotice({ text: 'Đã lưu tiêu chí Time to Market.', type: 'success' }); await load(); } catch (error) { setNotice({ text: error instanceof Error ? error.message : 'Không thể lưu tiêu chí Time to Market.', type: 'error' }); } finally { setSaving(false); } };
  const remove = async () => { if (!deleteTarget) return; setSaving(true); try { const endpoint = deleteTarget.kind === 'rule' ? `/api/status-alert-rules?id=${deleteTarget.id}` : `/api/ttm-policies?id=${deleteTarget.id}`; const response = await fetch(endpoint, { method: 'DELETE' }); const payload: unknown = await response.json(); if (!response.ok) throw new Error(readError(payload, 'Không thể xóa cấu hình.')); setDeleteTarget(null); setRuleModal(false); setPolicyModal(false); setNotice({ text: 'Đã xóa cấu hình.', type: 'success' }); await load(); } catch (error) { setNotice({ text: error instanceof Error ? error.message : 'Không thể xóa cấu hình.', type: 'error' }); } finally { setSaving(false); } };
  const ruleOptions = EPIC_COMPLEXITY_TYPES.map((value) => ({ value, label: typeLabel(value) }));
  const { sortKey: ruleSortKey, toggleSort: toggleRuleSort, directionFor: ruleSortDirection } = useSortableList<RuleSortKey>('epicComplexityType');
  const ruleSortValue = (rule: StatusAlertRule, key: RuleSortKey) => (key === 'status' ? (rule.isActive ? 'active' : 'inactive') : rule[key]);
  const sortedRules = [...rules].sort((a, b) => compareValues(ruleSortValue(a, ruleSortKey), ruleSortValue(b, ruleSortKey), ruleSortDirection(ruleSortKey) ?? 'asc'));
  const { sortKey: policySortKey, toggleSort: togglePolicySort, directionFor: policySortDirection } = useSortableList<PolicySortKey>('ttmType');
  const policySortValue = (policy: TtmPolicy, key: PolicySortKey) => (key === 'status' ? (policy.isActive ? 'active' : 'inactive') : policy[key]);
  const sortedPolicies = [...policies].sort((a, b) => compareValues(policySortValue(a, policySortKey), policySortValue(b, policySortKey), policySortDirection(policySortKey) ?? 'asc'));
  return <div className="flex flex-col gap-6">
    {notice && <Alert title={notice.type === 'success' ? 'Thành công' : 'Lỗi'} variant={notice.type === 'success' ? 'success' : 'error'}>{notice.text}</Alert>}
    <Card><CardHeader><div><CardTitle>Quy tắc cảnh báo Epic</CardTitle><p className="mt-1 text-fb-text-secondary">Mốc cảnh báo sớm và muộn tính từ Start Date. Deadline TTM được quản lý riêng bên dưới.</p></div><Button icon={<Plus className="size-4" weight="bold" />} onClick={() => { setEditingRule(null); setRuleForm(EMPTY_RULE); setRuleModal(true); }} size="sm">Thêm rule</Button></CardHeader><CardBody>{loading ? <TableSkeleton rows={4} /> : rules.length === 0 ? <EmptyState title="Chưa có rule cảnh báo" /> : <TableContainer><Table className="min-w-[760px]"><THead><TR>
        <TH>STT</TH>
        <TH sortDirection={ruleSortDirection('epicComplexityType')} onClick={() => toggleRuleSort('epicComplexityType')}>Loại Epic</TH>
        <TH sortDirection={ruleSortDirection('epicStatus')} onClick={() => toggleRuleSort('epicStatus')}>Trạng thái Epic</TH>
        <TH sortDirection={ruleSortDirection('earlyAlertOffsetDays')} onClick={() => toggleRuleSort('earlyAlertOffsetDays')}>Cảnh báo sớm</TH>
        <TH sortDirection={ruleSortDirection('lateAlertOffsetDays')} onClick={() => toggleRuleSort('lateAlertOffsetDays')}>Cảnh báo muộn</TH>
        <TH className="text-center" sortDirection={ruleSortDirection('status')} onClick={() => toggleRuleSort('status')}>Trạng thái</TH>
        <TH className="text-center">Hành động</TH>
      </TR></THead><TBody>{sortedRules.map((rule, index) => <TR key={rule.id}><TD>{index + 1}</TD><TD>{typeLabel(rule.epicComplexityType)}</TD><TD>{rule.epicStatus}</TD><TD>{offsetLabel(rule.earlyAlertOffsetDays)}</TD><TD>{offsetLabel(rule.lateAlertOffsetDays)}</TD><TD className="text-center"><Badge variant={rule.isActive ? 'success' : 'neutral'}>{rule.isActive ? 'Active' : 'Inactive'}</Badge></TD><TD><div className="flex justify-center"><TableAction icon={<PencilSimple className="size-4" />} onClick={() => { setEditingRule(rule.id); setRuleForm({ earlyAlertOffsetDays: rule.earlyAlertOffsetDays, epicComplexityType: rule.epicComplexityType, epicStatus: rule.epicStatus, isActive: rule.isActive, lateAlertOffsetDays: rule.lateAlertOffsetDays }); setRuleModal(true); }} variant="info">Chỉnh sửa</TableAction></div></TD></TR>)}</TBody></Table></TableContainer>}</CardBody></Card>
    <Card><CardHeader><div><CardTitle>Tiêu chí Time to Market</CardTitle><p className="mt-1 text-fb-text-secondary">Deadline được tính bằng số ngày làm việc từ trường From đến trường To của từng loại Epic.</p></div><Button icon={<Plus className="size-4" weight="bold" />} onClick={() => { setEditingPolicy(null); setPolicyForm(EMPTY_POLICY); setPolicyModal(true); }} size="sm">Thêm tiêu chí</Button></CardHeader><CardBody>{loading ? <TableSkeleton rows={4} /> : policies.length === 0 ? <EmptyState title="Chưa có tiêu chí Time to Market" /> : <TableContainer><Table className="min-w-[860px]"><THead><TR>
        <TH>STT</TH>
        <TH sortDirection={policySortDirection('ttmType')} onClick={() => togglePolicySort('ttmType')}>Loại TTM</TH>
        <TH sortDirection={policySortDirection('epicComplexityType')} onClick={() => togglePolicySort('epicComplexityType')}>Loại Epic</TH>
        <TH sortDirection={policySortDirection('fromTtmField')} onClick={() => togglePolicySort('fromTtmField')}>From TTM Field</TH>
        <TH sortDirection={policySortDirection('toTtmField')} onClick={() => togglePolicySort('toTtmField')}>To TTM Field</TH>
        <TH sortDirection={policySortDirection('workingDays')} onClick={() => togglePolicySort('workingDays')}>Số ngày làm việc</TH>
        <TH className="text-center" sortDirection={policySortDirection('status')} onClick={() => togglePolicySort('status')}>Trạng thái</TH>
        <TH className="text-center">Hành động</TH>
      </TR></THead><TBody>{sortedPolicies.map((policy, index) => <TR key={policy.id}><TD>{index + 1}</TD><TD>{policy.ttmType === 'TTM_CNTT' ? 'TTM-CNTT' : 'TTM-E2E'}</TD><TD>{typeLabel(policy.epicComplexityType)}</TD><TD>{policy.fromTtmField}</TD><TD>{policy.toTtmField}</TD><TD>{policy.workingDays}</TD><TD className="text-center"><Badge variant={policy.isActive ? 'success' : 'neutral'}>{policy.isActive ? 'Active' : 'Inactive'}</Badge></TD><TD><div className="flex justify-center"><TableAction icon={<PencilSimple className="size-4" />} onClick={() => { setEditingPolicy(policy.id); setPolicyForm({ epicComplexityType: policy.epicComplexityType, fromTtmField: policy.fromTtmField, isActive: policy.isActive, toTtmField: policy.toTtmField, ttmType: policy.ttmType, workingDays: policy.workingDays }); setPolicyModal(true); }} variant="info">Chỉnh sửa</TableAction></div></TD></TR>)}</TBody></Table></TableContainer>}</CardBody></Card>
    <Modal isOpen={ruleModal} maxWidth="sm" onClose={() => setRuleModal(false)} title={editingRule === null ? 'Thêm rule cảnh báo' : 'Chỉnh sửa rule cảnh báo'} footer={<><Button onClick={() => setRuleModal(false)} variant="outline">Hủy</Button>{editingRule !== null && <Button icon={<Trash className="size-4" />} onClick={() => setDeleteTarget({ id: editingRule, kind: 'rule', label: ruleForm.epicStatus })} variant="danger">Xóa tiêu chí</Button>}<Button isLoading={saving} onClick={saveRule}>Lưu cấu hình</Button></>}><div className="flex flex-col gap-4">{editingRule === null ? <><Select label="Loại Epic" options={ruleOptions} value={ruleForm.epicComplexityType} onChange={(e) => setRuleForm((x) => ({ ...x, epicComplexityType: e.target.value as StatusAlertRuleInput['epicComplexityType'] }))} /><Input label="Trạng thái Epic" required maxLength={50} value={ruleForm.epicStatus} onChange={(e) => setRuleForm((x) => ({ ...x, epicStatus: e.target.value }))} /></> : <div className="rounded-md border border-fb-border bg-fb-surface-muted px-3 py-2">{typeLabel(ruleForm.epicComplexityType)} · {ruleForm.epicStatus}</div>}<Input label="Offset cảnh báo sớm" type="number" min={0} required value={ruleForm.earlyAlertOffsetDays} onChange={(e) => setRuleForm((x) => ({ ...x, earlyAlertOffsetDays: Number(e.target.value) || 0 }))} /><Input label="Offset cảnh báo muộn" type="number" min={0} required value={ruleForm.lateAlertOffsetDays} onChange={(e) => setRuleForm((x) => ({ ...x, lateAlertOffsetDays: Number(e.target.value) || 0 }))} /><label className="ui-check"><input type="checkbox" checked={ruleForm.isActive} onChange={(e) => setRuleForm((x) => ({ ...x, isActive: e.target.checked }))} />Rule đang hoạt động</label><p className="ui-helper">Cảnh báo sớm phải nhỏ hơn cảnh báo muộn.</p></div></Modal>
    <Modal isOpen={policyModal} maxWidth="sm" onClose={() => setPolicyModal(false)} title={editingPolicy === null ? 'Thêm tiêu chí Time to Market' : 'Chỉnh sửa tiêu chí Time to Market'} footer={<><Button onClick={() => setPolicyModal(false)} variant="outline">Hủy</Button>{editingPolicy !== null && <Button icon={<Trash className="size-4" />} onClick={() => setDeleteTarget({ id: editingPolicy, kind: 'policy', label: policyForm.ttmType })} variant="danger">Xóa tiêu chí</Button>}<Button isLoading={saving} onClick={savePolicy}>Lưu cấu hình</Button></>}><div className="flex flex-col gap-4"><Select label="Loại TTM" options={TTM_TYPES.map((x) => ({ value: x, label: x === 'TTM_CNTT' ? 'TTM-CNTT' : 'TTM-E2E' }))} value={policyForm.ttmType} onChange={(e) => setPolicyForm((x) => ({ ...x, ttmType: e.target.value as TtmPolicyInput['ttmType'] }))} /><Select label="Loại Epic" options={ruleOptions} value={policyForm.epicComplexityType} onChange={(e) => setPolicyForm((x) => ({ ...x, epicComplexityType: e.target.value as TtmPolicyInput['epicComplexityType'] }))} /><Input label="From TTM Field" maxLength={100} required value={policyForm.fromTtmField} onChange={(e) => setPolicyForm((x) => ({ ...x, fromTtmField: e.target.value }))} /><Input label="To TTM Field" maxLength={100} required value={policyForm.toTtmField} onChange={(e) => setPolicyForm((x) => ({ ...x, toTtmField: e.target.value }))} /><Input label="Số ngày làm việc" type="number" min={1} required value={policyForm.workingDays} onChange={(e) => setPolicyForm((x) => ({ ...x, workingDays: Number(e.target.value) || 0 }))} /><label className="ui-check"><input type="checkbox" checked={policyForm.isActive} onChange={(e) => setPolicyForm((x) => ({ ...x, isActive: e.target.checked }))} />Tiêu chí đang hoạt động</label></div></Modal>
    <ConfirmDialog isOpen={deleteTarget !== null} onClose={() => setDeleteTarget(null)} onConfirm={() => void remove()} title="Xóa tiêu chí" description={`Bạn có chắc muốn xóa “${deleteTarget?.label ?? ''}”? Thao tác này xác nhận một bước.`} confirmLabel="Xóa" steps={1} />
  </div>;
}
