import { NextRequest, NextResponse } from 'next/server';
import { AuthError, createManagedUser, deleteInactiveManagedUsers, deleteManagedUser, listManagedUsers, requireUser, resetUserPassword, updateManagedUser } from '@/lib/auth-service';
import { USER_ROLES } from '@/lib/auth-types';
import type { UserInput, UserRole } from '@/lib/auth-types';
import { listDomains, listProjects } from '@/lib/master-data-service';

function isRecord(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null; }
function isIdList(value: unknown): value is number[] { return Array.isArray(value) && value.every((item) => Number.isInteger(item) && item > 0); }

function parseUser(body: unknown, requirePassword: boolean): { error: string } | { value: UserInput } {
  if (!isRecord(body) || typeof body.email !== 'string' || typeof body.fullName !== 'string' || typeof body.role !== 'string' || typeof body.isActive !== 'boolean' || !isIdList(body.domainIds) || (body.isActive && body.domainIds.length === 0) || new Set(body.domainIds).size !== body.domainIds.length || !isIdList(body.projectIds) || new Set(body.projectIds).size !== body.projectIds.length) return { error: 'Dữ liệu người dùng không hợp lệ. User active phải thuộc ít nhất một Domain; Domain và Dự án không được trùng lặp.' };
  const email = body.email.trim().toLowerCase();
  if (!/^[^\s@]+@mbbank\.com\.vn$/i.test(email) || body.fullName.trim().length === 0 || body.fullName.trim().length > 255 || !USER_ROLES.includes(body.role as UserRole)) return { error: 'Email MB Bank, họ tên hoặc role không hợp lệ.' };
  if (requirePassword && (typeof body.password !== 'string' || body.password.length < 8 || body.password.length > 256)) return { error: 'Mật khẩu phải có từ 8 đến 256 ký tự.' };
  return { value: { email, fullName: body.fullName.trim(), role: body.role as UserRole, isActive: body.isActive, domainIds: body.domainIds, projectIds: [...new Set(body.projectIds)], ...(typeof body.password === 'string' ? { password: body.password } : {}) } };
}

async function hasActiveDomains(ids: number[]): Promise<boolean> {
  const activeDomainIds = new Set((await listDomains()).filter((domain) => domain.isActive).map((domain) => domain.id));
  return ids.every((id) => activeDomainIds.has(id));
}
async function hasProjects(ids: number[]): Promise<boolean> {
  const projectIds = new Set((await listProjects()).map((project) => project.id));
  return ids.every((id) => projectIds.has(id));
}
function errorResponse(error: unknown): NextResponse | null { if (error instanceof AuthError) return NextResponse.json({ error: error.code === 'FORBIDDEN' ? 'Bạn không có quyền quản lý user.' : 'Chưa đăng nhập.' }, { status: error.code === 'FORBIDDEN' ? 403 : 401 }); return null; }

export async function GET(request: NextRequest) { try { await requireUser(request, ['ADMIN', 'SUPERADMIN']); return NextResponse.json(await listManagedUsers()); } catch (error) { return errorResponse(error) ?? NextResponse.json({ error: 'Không thể tải danh sách user.' }, { status: 500 }); } }
export async function POST(request: NextRequest) { try { await requireUser(request, ['ADMIN', 'SUPERADMIN']); const parsed = parseUser(await request.json(), true); if ('error' in parsed) return NextResponse.json(parsed, { status: 400 }); if (!await hasActiveDomains(parsed.value.domainIds)) return NextResponse.json({ error: 'Một hoặc nhiều Domain không tồn tại hoặc đã ngừng hoạt động.' }, { status: 400 }); if (!await hasProjects(parsed.value.projectIds)) return NextResponse.json({ error: 'Một hoặc nhiều Dự án không tồn tại.' }, { status: 400 }); return NextResponse.json(await createManagedUser(parsed.value), { status: 201 }); } catch (error) { if (isRecord(error) && error.code === '23505') return NextResponse.json({ error: 'Email đã tồn tại.' }, { status: 409 }); return errorResponse(error) ?? NextResponse.json({ error: 'Không thể tạo user.' }, { status: 500 }); } }
export async function PUT(request: NextRequest) { try { await requireUser(request, ['ADMIN', 'SUPERADMIN']); const body: unknown = await request.json(); if (!isRecord(body) || !Number.isInteger(body.id) || (body.id as number) <= 0) return NextResponse.json({ error: 'ID user không hợp lệ.' }, { status: 400 }); const parsed = parseUser(body, false); if ('error' in parsed) return NextResponse.json(parsed, { status: 400 }); if (!await hasActiveDomains(parsed.value.domainIds)) return NextResponse.json({ error: 'Một hoặc nhiều Domain không tồn tại hoặc đã ngừng hoạt động.' }, { status: 400 }); if (!await hasProjects(parsed.value.projectIds)) return NextResponse.json({ error: 'Một hoặc nhiều Dự án không tồn tại.' }, { status: 400 }); const user = await updateManagedUser(body.id as number, parsed.value); return user ? NextResponse.json(user) : NextResponse.json({ error: 'Không tìm thấy user.' }, { status: 404 }); } catch (error) { return errorResponse(error) ?? NextResponse.json({ error: 'Không thể cập nhật user.' }, { status: 500 }); } }
export async function PATCH(request: NextRequest) { try { const actor = await requireUser(request, ['ADMIN', 'SUPERADMIN']); const body: unknown = await request.json(); if (!isRecord(body) || !Number.isInteger(body.id) || typeof body.password !== 'string' || body.password.length < 8 || body.password.length > 256) return NextResponse.json({ error: 'Dữ liệu cấp lại mật khẩu không hợp lệ.' }, { status: 400 }); const updated = await resetUserPassword(body.id as number, body.password, actor.id); return updated ? NextResponse.json({ success: true }) : NextResponse.json({ error: 'Không tìm thấy user.' }, { status: 404 }); } catch (error) { return errorResponse(error) ?? NextResponse.json({ error: 'Không thể cấp lại mật khẩu.' }, { status: 500 }); } }
export async function DELETE(request: NextRequest) { try { await requireUser(request, ['ADMIN', 'SUPERADMIN']); const body: unknown = await request.json().catch(() => null); if (isRecord(body) && Array.isArray(body.ids) && body.ids.length > 0 && body.ids.length <= 100 && body.ids.every((id) => Number.isInteger(id) && id > 0)) return NextResponse.json({ success: true, deleted: await deleteInactiveManagedUsers(body.ids as number[]) }); const id = Number(new URL(request.url).searchParams.get('id')); if (!Number.isInteger(id) || id <= 0) return NextResponse.json({ error: 'ID user không hợp lệ.' }, { status: 400 }); return (await deleteManagedUser(id)) ? NextResponse.json({ success: true }) : NextResponse.json({ error: 'Không tìm thấy user.' }, { status: 404 }); } catch (error) { return errorResponse(error) ?? NextResponse.json({ error: 'Không thể xóa user.' }, { status: 500 }); } }
